### ISSUE TITLE
Simple use case?

### ISSUE THREAD

**Issue by sohrabtowfighi** [folivetti/ITSR#1]
Hi

Would it be possible to have documented the simplest way to use this code against a CSV file for symbolic regression? This might be in the code already but I am having trouble navigating.

Thank you!

**Comment by folivetti** [comment]
Of course, I'm out of office right now but give me a week and I'll add this info together with some sample usage scripts

**Comment by folivetti** [comment]
Just updated the folder SymTree with a sample script for the Python version, see:

https://github.com/folivetti/ITSR/tree/master/SymTree

Let me know if you have any issues!
